/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Denotes that the annotated member checks whether a specific aconfig flag is enabled.
 *
 * <p>This annotation is used by tools such as Metalava and Android Lint to inform call-chain
 * analysis that a flag check has been performed. Callers of APIs annotated with
 * {@code @RequiresFlag} or {@code @FlaggedApi} will not trigger lint warnings if a member
 * annotated with {@code @ChecksFlag} for the corresponding flag is invoked in their call chain.
 *
 * <p>The flag can be specified via {@link #value()}, or it can be passed in as a parameter to
 * the method; in that case, the parameter containing the flag name should be specified via
 * {@link #parameter()}, where the first parameter is numbered 0.
 *
 * <p>Examples:
 * <pre><code>
 *  // Simple flag check method (e.g. generated by Aconfig or a helper method):
 *  &#64;ChecksFlag(Flags.FLAG_FOOBAR)
 *  public static boolean isFoobarEnabled() {
 *      return Flags.foobar();
 *  }
 *
 *  // Boolean constant field caching a flag value:
 *  &#64;ChecksFlag(Flags.FLAG_FOOBAR)
 *  public static final boolean IS_FOOBAR_ENABLED = Flags.foobar();
 * </code></pre>
 */
@Documented
@Retention(CLASS)
@Target({METHOD, FIELD})
public @interface ChecksFlag {
    /**
     * The aconfig flag used to check feature enablement. Use the aconfig
     * auto-generated constant to refer to the flag, e.g. {@code @ChecksFlag(Flags.FLAG_FOOBAR)}.
     */
    String value() default "";
}