/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.tools.metalava.model.text

import com.android.tools.metalava.model.Codebase
import com.android.tools.metalava.reporter.Issues

/**
 * Provides support for reporting recoverable errors while parsing type items.
 *
 * A recoverable error is one that is not caused by syntax issues and there is an obvious way of
 * moving past after reporting the problem, e.g. an [Issues.UNQUALIFIED_TYPE_ERROR] could be
 * bypassed by assuming that it is a valid class and creating a stub in the [Codebase].
 *
 * This is primarily for testing and reading historical versions which may not quite match the
 * expected format. In normal use types are nearly always generated by Metalava and so should always
 * be readable by Metalava. The exception would be types which appear in an annotation instance
 * specified on the command line.
 */
internal interface TypeItemParserErrorReporter {
    /** Report recoverable errors encountered while parsing. */
    fun report(issue: Issues.Issue, message: String)

    /** Report recoverable errors encountered while parsing, using a generic issue. */
    fun report(message: String) = report(Issues.TYPE_PARSE_ERROR, message)

    companion object {
        /**
         * A [TypeItemParserErrorReporter] that throws an exception at the first error it
         * encounters.
         */
        val THROWING =
            object : TypeItemParserErrorReporter {
                override fun report(issue: Issues.Issue, message: String) {
                    error("$message [$issue]")
                }
            }
    }
}
